apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub1
spec:
  type: pubsub.in-memory
  version: v1
  metadata: []

---

# apiVersion: dapr.io/v1alpha1
# kind: Component
# metadata:
#   name: pubsub2
# spec:
#   type: pubsub.in-memory
#   version: v1
#   metadata: []

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub2
spec:
  type: pubsub.azure.servicebus.topics
  version: v1
  metadata:
  - name: connectionString
    value: "<connectionString>"
  - name: disableEntityManagement
    value: false
  - name: consumerID
    value: demosub1         # subscription name in topic

---

apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: sub1
spec:
  topic: topic1
  routes: 
    default: /test/sub1
  pubsubname: pubsub1
scopes:
- demo

---

apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: sub2
spec:
  topic: topic2
  routes: 
    default: /test/sub2
  pubsubname: pubsub2
scopes:
- demo
