apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  # type: pubsub.redis
  # version: v1
  # metadata:
  # - name: redisHost
  #   value: localhost:6379
  # - name: redisPassword
  #   value: ""
  # type: pubsub.azure.servicebus.topics		# metadata has 'Metadata.' prefix
  # version: v1
  # metadata:
  # - name: namespaceName
  #   value: dev-vdp-common-sbsn-01-weu.servicebus.windows.net
  # - name: consumerID
  #   value: pubsubdemo
  type: pubsub.in-memory		# no metadata support
  version: v1
  metadata: []

