name: Deploy docfx content to Pages

on:
  push:
    branches: ["master"]
    paths: ["docs/**"]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.406'
        
    - name: Update submodules
      run: |
        git clone -b master --single-branch --depth 1 git:${{ secrets.GITHUB_TOKEN }}@github.com:veracity-engineering/SolutionPackageDoc.wiki.git docs/articles
        git clone -b master --single-branch --depth 1 git:${{ secrets.GITHUB_TOKEN }}@github.com:veracity-engineering/SolutionPackage.git docs/src
        git clone -b gh-pages --single-branch --depth 1 git:${{ secrets.GITHUB_TOKEN }}@github.com:veracity-engineering/SolutionPackageDoc.git docs/_site
      
    - name: Generate docs
      run: |
        echo '{"sdk":{"version": "6.0.406"}}' > global.json
        
        echo "::debug::Restore nuget packages"
        pushd src
        dotnet restore
        popd
        
        echo "::debug::Update docfx"
        dotnet tool update -g docfx
        
        echo "::debug::Generate docfx files"
        docfx docs/docfx.json 
        
    - name: Publish gh-pages
      run: |
        cd docs/_site
        
        echo "::debug::Add new files to git"
        git fetch
        git add .
        
        echo "::debug::Commit changes to git"
        git config user.email "actions-bot@users.noreply.github.com"
        git config user.name "github actions bot"
        git commit -m "Update docs" || echo "No change to commit"
        
        echo "::debug::Push commit to remote"
        git push git:${{ secrets.GITHUB_TOKEN }}@github.com:veracity-engineering/SolutionPackageDoc.git HEAD:gh-pages
