name: Deploy docfx content to Pages

on:
  push:
    branches: ["main"]
    paths: ["docs/**"]
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.406'
        
    - name: Update submodules
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote
      
    - name: Generate docs
      run: |
        echo '{"sdk":{"version": "6.0.406"}}' > global.json
        
        echo "::debug::Restore nuget packages"
        dotnet restore src/DNVGL.SolutionPackage.sln
        
        echo "::debug::Update docfx"
        dotnet tool update -g docfx
        
        echo "::debug::Generate docfx files"
        docfx docs/docfx.json 
        
    - name: publish gh-pages
      run: |
        cd docs/_site
        
        echo "::debug::Add new files to git"
        git fetch
        git add .
        
        echo "::debug::Commit changes to git"
        git config user.email "github-actions-bot@dnv.com"
        git config user.name "github actions boot"
        git commit -m "Update docs" || echo "No change to commit"
        
        echo "::debug::Push commit to remote"
        git push https://bot:${{ secrets.GITHUB_TOKEN }}@github.com/veracity-engineering/SolutionPackage.git HEAD:gh-pages
